const APP_ID = '6800162514';
const APP_SLUG = 'the-truth-al-haq';

const countries = [
  { name: 'Afghanistan', code: 'af', flag: '🇦🇫' },
  { name: 'Albania', code: 'al', flag: '🇦🇱' },
  { name: 'Algeria', code: 'dz', flag: '🇩🇿' },
  { name: 'Angola', code: 'ao', flag: '🇦🇴' },
  { name: 'Anguilla', code: 'ai', flag: '🇦🇮' },
  { name: 'Antigua and Barbuda', code: 'ag', flag: '🇦🇬' },
  { name: 'Argentina', code: 'ar', flag: '🇦🇷' },
  { name: 'Armenia', code: 'am', flag: '🇦🇲' },
  { name: 'Australia', code: 'au', flag: '🇦🇺' },
  { name: 'Azerbaijan', code: 'az', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'bs', flag: '🇧🇸' },
  { name: 'Bahrain', code: 'bh', flag: '🇧🇭' },
  { name: 'Barbados', code: 'bb', flag: '🇧🇧' },
  { name: 'Belarus', code: 'by', flag: '🇧🇾' },
  { name: 'Belize', code: 'bz', flag: '🇧🇿' },
  { name: 'Benin', code: 'bj', flag: '🇧🇯' },
  { name: 'Bermuda', code: 'bm', flag: '🇧🇲' },
  { name: 'Bhutan', code: 'bt', flag: '🇧🇹' },
  { name: 'Bolivia', code: 'bo', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'ba', flag: '🇧🇦' },
  { name: 'Botswana', code: 'bw', flag: '🇧🇼' },
  { name: 'Brazil', code: 'br', flag: '🇧🇷' },
  { name: 'British Virgin Islands', code: 'vg', flag: '🇻🇬' },
  { name: 'Brunei', code: 'bn', flag: '🇧🇳' },
  { name: 'Burkina Faso', code: 'bf', flag: '🇧🇫' },
  { name: 'Cambodia', code: 'kh', flag: '🇰🇭' },
  { name: 'Cameroon', code: 'cm', flag: '🇨🇲' },
  { name: 'Canada', code: 'ca', flag: '🇨🇦' },
  { name: 'Cape Verde', code: 'cv', flag: '🇨🇻' },
  { name: 'Cayman Islands', code: 'ky', flag: '🇰🇾' },
  { name: 'Chad', code: 'td', flag: '🇹🇩' },
  { name: 'Chile', code: 'cl', flag: '🇨🇱' },
  { name: 'China mainland', code: 'cn', flag: '🇨🇳' },
  { name: 'Colombia', code: 'co', flag: '🇨🇴' },
  { name: 'Congo, Democratic Republic of the', code: 'cd', flag: '🇨🇩' },
  { name: 'Congo, Republic of the', code: 'cg', flag: '🇨🇬' },
  { name: 'Costa Rica', code: 'cr', flag: '🇨🇷' },
  { name: "Côte d'Ivoire", code: 'ci', flag: '🇨🇮' },
  { name: 'Dominica', code: 'dm', flag: '🇩🇲' },
  { name: 'Dominican Republic', code: 'do', flag: '🇩🇴' },
  { name: 'Ecuador', code: 'ec', flag: '🇪🇨' },
  { name: 'Egypt', code: 'eg', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'sv', flag: '🇸🇻' },
  { name: 'Eswatini', code: 'sz', flag: '🇸🇿' },
  { name: 'Fiji', code: 'fj', flag: '🇫🇯' },
  { name: 'Gabon', code: 'ga', flag: '🇬🇦' },
  { name: 'Gambia', code: 'gm', flag: '🇬🇲' },
  { name: 'Georgia', code: 'ge', flag: '🇬🇪' },
  { name: 'Ghana', code: 'gh', flag: '🇬🇭' },
  { name: 'Grenada', code: 'gd', flag: '🇬🇩' },
  { name: 'Guatemala', code: 'gt', flag: '🇬🇹' },
  { name: 'Guinea-Bissau', code: 'gw', flag: '🇬🇼' },
  { name: 'Guyana', code: 'gy', flag: '🇬🇾' },
  { name: 'Honduras', code: 'hn', flag: '🇭🇳' },
  { name: 'Hong Kong', code: 'hk', flag: '🇭🇰' },
  { name: 'Iceland', code: 'is', flag: '🇮🇸' },
  { name: 'India', code: 'in', flag: '🇮🇳' },
  { name: 'Indonesia', code: 'id', flag: '🇮🇩' },
  { name: 'Iraq', code: 'iq', flag: '🇮🇶' },
  { name: 'Israel', code: 'il', flag: '🇮🇱' },
  { name: 'Jamaica', code: 'jm', flag: '🇯🇲' },
  { name: 'Japan', code: 'jp', flag: '🇯🇵' },
  { name: 'Jordan', code: 'jo', flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'kz', flag: '🇰🇿' },
  { name: 'Kenya', code: 'ke', flag: '🇰🇪' },
  { name: 'Korea, Republic of', code: 'kr', flag: '🇰🇷' },
  { name: 'Kosovo', code: 'xk', flag: '🇽🇰' },
  { name: 'Kuwait', code: 'kw', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'kg', flag: '🇰🇬' },
  { name: 'Laos', code: 'la', flag: '🇱🇦' },
  { name: 'Lebanon', code: 'lb', flag: '🇱🇧' },
  { name: 'Liberia', code: 'lr', flag: '🇱🇷' },
  { name: 'Libya', code: 'ly', flag: '🇱🇾' },
  { name: 'Macau', code: 'mo', flag: '🇲🇴' },
  { name: 'Madagascar', code: 'mg', flag: '🇲🇬' },
  { name: 'Malawi', code: 'mw', flag: '🇲🇼' },
  { name: 'Malaysia', code: 'my', flag: '🇲🇾' },
  { name: 'Maldives', code: 'mv', flag: '🇲🇻' },
  { name: 'Mali', code: 'ml', flag: '🇲🇱' },
  { name: 'Mauritania', code: 'mr', flag: '🇲🇷' },
  { name: 'Mauritius', code: 'mu', flag: '🇲🇺' },
  { name: 'Mexico', code: 'mx', flag: '🇲🇽' },
  { name: 'Micronesia', code: 'fm', flag: '🇫🇲' },
  { name: 'Moldova', code: 'md', flag: '🇲🇩' },
  { name: 'Mongolia', code: 'mn', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'me', flag: '🇲🇪' },
  { name: 'Montserrat', code: 'ms', flag: '🇲🇸' },
  { name: 'Morocco', code: 'ma', flag: '🇲🇦' },
  { name: 'Mozambique', code: 'mz', flag: '🇲🇿' },
  { name: 'Myanmar', code: 'mm', flag: '🇲🇲' },
  { name: 'Namibia', code: 'na', flag: '🇳🇦' },
  { name: 'Nauru', code: 'nr', flag: '🇳🇷' },
  { name: 'Nepal', code: 'np', flag: '🇳🇵' },
  { name: 'New Zealand', code: 'nz', flag: '🇳🇿' },
  { name: 'Nicaragua', code: 'ni', flag: '🇳🇮' },
  { name: 'Niger', code: 'ne', flag: '🇳🇪' },
  { name: 'Nigeria', code: 'ng', flag: '🇳🇬' },
  { name: 'North Macedonia', code: 'mk', flag: '🇲🇰' },
  { name: 'Norway', code: 'no', flag: '🇳🇴' },
  { name: 'Oman', code: 'om', flag: '🇴🇲' },
  { name: 'Pakistan', code: 'pk', flag: '🇵🇰' },
  { name: 'Palau', code: 'pw', flag: '🇵🇼' },
  { name: 'Panama', code: 'pa', flag: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'pg', flag: '🇵🇬' },
  { name: 'Paraguay', code: 'py', flag: '🇵🇾' },
  { name: 'Peru', code: 'pe', flag: '🇵🇪' },
  { name: 'Philippines', code: 'ph', flag: '🇵🇭' },
  { name: 'Qatar', code: 'qa', flag: '🇶🇦' },
  { name: 'Russia', code: 'ru', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'rw', flag: '🇷🇼' },
  { name: 'São Tomé and Príncipe', code: 'st', flag: '🇸🇹' },
  { name: 'Saudi Arabia', code: 'sa', flag: '🇸🇦' },
  { name: 'Senegal', code: 'sn', flag: '🇸🇳' },
  { name: 'Serbia', code: 'rs', flag: '🇷🇸' },
  { name: 'Seychelles', code: 'sc', flag: '🇸🇨' },
  { name: 'Sierra Leone', code: 'sl', flag: '🇸🇱' },
  { name: 'Singapore', code: 'sg', flag: '🇸🇬' },
  { name: 'Solomon Islands', code: 'sb', flag: '🇸🇧' },
  { name: 'South Africa', code: 'za', flag: '🇿🇦' },
  { name: 'Sri Lanka', code: 'lk', flag: '🇱🇰' },
  { name: 'St. Kitts and Nevis', code: 'kn', flag: '🇰🇳' },
  { name: 'St. Lucia', code: 'lc', flag: '🇱🇨' },
  { name: 'St. Vincent and the Grenadines', code: 'vc', flag: '🇻🇨' },
  { name: 'Suriname', code: 'sr', flag: '🇸🇷' },
  { name: 'Switzerland', code: 'ch', flag: '🇨🇭' },
  { name: 'Taiwan', code: 'tw', flag: '🇹🇼' },
  { name: 'Tajikistan', code: 'tj', flag: '🇹🇯' },
  { name: 'Tanzania', code: 'tz', flag: '🇹🇿' },
  { name: 'Thailand', code: 'th', flag: '🇹🇭' },
  { name: 'Tonga', code: 'to', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: 'tt', flag: '🇹🇹' },
  { name: 'Tunisia', code: 'tn', flag: '🇹🇳' },
  { name: 'Türkiye', code: 'tr', flag: '🇹🇷' },
  { name: 'Turkmenistan', code: 'tm', flag: '🇹🇲' },
  { name: 'Turks and Caicos Islands', code: 'tc', flag: '🇹🇨' },
  { name: 'Uganda', code: 'ug', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'ua', flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'ae', flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'gb', flag: '🇬🇧' },
  { name: 'United States', code: 'us', flag: '🇺🇸' },
  { name: 'Uruguay', code: 'uy', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'uz', flag: '🇺🇿' },
  { name: 'Vanuatu', code: 'vu', flag: '🇻🇺' },
  { name: 'Venezuela', code: 've', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'vn', flag: '🇻🇳' },
  { name: 'Yemen', code: 'ye', flag: '🇾🇪' },
  { name: 'Zambia', code: 'zm', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'zw', flag: '🇿🇼' }
];

function renderCountries(filter = '') {
  const grid = document.getElementById('country-grid');
  if (!grid) return;
  const term = filter.toLowerCase().trim();
  const filtered = term
    ? countries.filter(c => c.name.toLowerCase().includes(term))
    : countries;

  grid.innerHTML = filtered.map(c => `
    <a class="country-card" href="https://apps.apple.com/${c.code}/app/${APP_SLUG}/${APP_ID}" target="_blank" rel="noopener" title="${c.name}">
      <span class="country-flag">${c.flag}</span>
      <span class="country-name">${c.name}</span>
    </a>
  `).join('');
}

document.addEventListener('DOMContentLoaded', () => {
  renderCountries();
  const search = document.getElementById('country-search');
  if (search) {
    search.addEventListener('input', (e) => renderCountries(e.target.value));
  }
});
